### ISSUE TITLE
Downtime

### ISSUE THREAD

**Issue by D063520** [ec-doris/EuKnowledgeGraph#102]
I finally was able to be there in a downtime period. I enabeled the debugging flag:

$wgShowExceptionDetails = true;

and I got this error:

MediaWiki internal error.

Original exception: [4c8fc43d688fc2a7cb787014] /wiki/Main_Page MWException from line 129 of /var/www/html/includes/MagicWord.php: Error: invalid magic word 'if'
Backtrace:
#0 /var/www/html/includes/MagicWordFactory.php(230): MagicWord->load(string)
#1 /var/www/html/includes/parser/Parser.php(4872): MagicWordFactory->get(string)
#2 /var/www/html/extensions/ParserFunctions/includes/Hooks.php(32): Parser->setFunctionHook(string, string, integer)
#3 /var/www/html/includes/HookContainer/HookContainer.php(329): MediaWiki\Extensions\ParserFunctions\Hooks::onParserFirstCallInit(Parser)
#4 /var/www/html/includes/HookContainer/HookContainer.php(132): MediaWiki\HookContainer\HookContainer->callLegacyHook(string, array, array, array)
#5 /var/www/html/includes/HookContainer/HookRunner.php(2960): MediaWiki\HookContainer\HookContainer->run(string, array)
#6 /var/www/html/includes/parser/Parser.php(532): MediaWiki\HookContainer\HookRunner->onParserFirstCallInit(Parser)
#7 /var/www/html/includes/parser/Parser.php(477): Parser->firstCallInit()
#8 /var/www/html/includes/parser/ParserFactory.php(142): Parser->__construct(MediaWiki\Config\ServiceOptions, MagicWordFactory, LanguageEn, ParserFactory, string, MediaWiki\SpecialPage\SpecialPageFactory, MediaWiki\Linker\LinkRendererFactory, NamespaceInfo, MediaWiki\Logger\LegacyLogger, MediaWiki\BadFileLookup, MediaWiki\Languages\LanguageConverterFactory, MediaWiki\HookContainer\HookContainer)
#9 /var/www/html/includes/ServiceWiring.php(817): ParserFactory->create()
#10 /var/www/html/vendor/wikimedia/services/src/ServiceContainer.php(447): Wikimedia\Services\ServiceContainer->{closure}(MediaWiki\MediaWikiServices)
#11 /var/www/html/vendor/wikimedia/services/src/ServiceContainer.php(416): Wikimedia\Services\ServiceContainer->createService(string)
#12 /var/www/html/includes/MediaWikiServices.php(1000): Wikimedia\Services\ServiceContainer->getService(string)
#13 /var/www/html/includes/cache/MessageCache.php(1266): MediaWiki\MediaWikiServices->getParser()
#14 /var/www/html/includes/cache/MessageCache.php(1245): MessageCache->getParser()
#15 /var/www/html/includes/language/Message.php(1287): MessageCache->transform(string, boolean, Language, Title)
#16 /var/www/html/includes/language/Message.php(894): Message->transformText(string)
#17 /var/www/html/includes/language/Message.php(954): Message->toString(string)
#18 /var/www/html/includes/OutputPage.php(944): Message->text()
#19 /var/www/html/includes/OutputPage.php(993): OutputPage->setHTMLTitle(Message)
#20 /var/www/html/includes/page/Article.php(662): OutputPage->setPageTitle(string)
#21 /var/www/html/includes/actions/ViewAction.php(80): Article->view()
#22 /var/www/html/includes/MediaWiki.php(532): ViewAction->show()
#23 /var/www/html/includes/MediaWiki.php(313): MediaWiki->performAction(Article, Title)
#24 /var/www/html/includes/MediaWiki.php(945): MediaWiki->performRequest()
#25 /var/www/html/includes/MediaWiki.php(548): MediaWiki->main()
#26 /var/www/html/index.php(53): MediaWiki->run()
#27 /var/www/html/index.php(46): wfIndexMain()
#28 {main}

Exception caught inside exception handler: [4c8fc43d688fc2a7cb787014] /wiki/Main_Page MWException from line 129 of /var/www/html/includes/MagicWord.php: Error: invalid magic word 'if'
Backtrace:
#0 /var/www/html/includes/MagicWordFactory.php(230): MagicWord->load(string)
#1 /var/www/html/includes/parser/Parser.php(4872): MagicWordFactory->get(string)
#2 /var/www/html/extensions/ParserFunctions/includes/Hooks.php(32): Parser->setFunctionHook(string, string, integer)
#3 /var/www/html/includes/HookContainer/HookContainer.php(329): MediaWiki\Extensions\ParserFunctions\Hooks::onParserFirstCallInit(Parser)
#4 /var/www/html/includes/HookContainer/HookContainer.php(132): MediaWiki\HookContainer\HookContainer->callLegacyHook(string, array, array, array)
#5 /var/www/html/includes/HookContainer/HookRunner.php(2960): MediaWiki\HookContainer\HookContainer->run(string, array)
#6 /var/www/html/includes/parser/Parser.php(532): MediaWiki\HookContainer\HookRunner->onParserFirstCallInit(Parser)
#7 /var/www/html/includes/parser/Parser.php(477): Parser->firstCallInit()
#8 /var/www/html/includes/parser/ParserFactory.php(142): Parser->__construct(MediaWiki\Config\ServiceOptions, MagicWordFactory, LanguageEn, ParserFactory, string, MediaWiki\SpecialPage\SpecialPageFactory, MediaWiki\Linker\LinkRendererFactory, NamespaceInfo, MediaWiki\Logger\LegacyLogger, MediaWiki\BadFileLookup, MediaWiki\Languages\LanguageConverterFactory, MediaWiki\HookContainer\HookContainer)
#9 /var/www/html/includes/ServiceWiring.php(817): ParserFactory->create()
#10 /var/www/html/vendor/wikimedia/services/src/ServiceContainer.php(447): Wikimedia\Services\ServiceContainer->{closure}(MediaWiki\MediaWikiServices)
#11 /var/www/html/vendor/wikimedia/services/src/ServiceContainer.php(416): Wikimedia\Services\ServiceContainer->createService(string)
#12 /var/www/html/includes/MediaWikiServices.php(1000): Wikimedia\Services\ServiceContainer->getService(string)
#13 /var/www/html/includes/cache/MessageCache.php(1266): MediaWiki\MediaWikiServices->getParser()
#14 /var/www/html/includes/cache/MessageCache.php(1245): MessageCache->getParser()
#15 /var/www/html/includes/language/Message.php(1287): MessageCache->transform(string, boolean, Language, Title)
#16 /var/www/html/includes/language/Message.php(894): Message->transformText(string)
#17 /var/www/html/includes/language/Message.php(954): Message->toString(string)
#18 /var/www/html/includes/OutputPage.php(944): Message->text()
#19 /var/www/html/includes/OutputPage.php(993): OutputPage->setHTMLTitle(Message)
#20 /var/www/html/includes/OutputPage.php(2658): OutputPage->setPageTitle(string)
#21 /var/www/html/includes/exception/MWException.php(179): OutputPage->prepareErrorPage(string)
#22 /var/www/html/includes/exception/MWException.php(231): MWException->reportHTML()
#23 /var/www/html/includes/exception/MWExceptionHandler.php(104): MWException->report()
#24 /var/www/html/includes/exception/MWExceptionHandler.php(185): MWExceptionHandler::report(MWException)
#25 /var/www/html/includes/MediaWiki.php(581): MWExceptionHandler::handleException(MWException, string)
#26 /var/www/html/index.php(53): MediaWiki->run()
#27 /var/www/html/index.php(46): wfIndexMain()
#28 {main}

which is related to the ParserFunctions extention. This is enabled to show example SPARQL queries in query service. I deactivate it and the wikibase was back. The side effect is that something is not rendered here now:

https://linkedopendata.eu/wiki/EuKnowledgeGraph:SPARQL_query_service/queries/examples

This is a temporary fix. If the pod will be filled we will see the problem again. I want to check though is this solves the downtime issues. I suspect that there is at least another reason that is cause by the database having problems.

**Comment by D063520** [comment]
Did not occur anymore, must be related to a change in the configuration of the kubernates machines.
